### ISSUE TITLE
설문지 폼 관련하여 질문 있습니다.

### ISSUE THREAD

**Issue by ParkYongHun** [2021-SMHRD-KDT-AI-1/whatToday#15]
CSS 에서 progress bar value 값을 바꿔주는 함수를 만들었는데 적용이 되지 않습니다..

div를 활성화 비활성화 하는 방법을 알고싶습니다. 그 방법을 토대로 한 화면에 설문내용을 하나씩 띄워주고싶고
답변을 하면 다음 설문으로 넘어가는걸 알고싶습니다.

**Comment by Koth100** [comment]
사용하지 않는 <form> 태그를 제거하여 해결
